server:
  port: 7999
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yinyyang/wip-springcloud-config-repo.git
          search-paths: properties
          default-label: master
