server:
  port: 8005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

spring:
  datasource:
    url: jdbc:mysql://192.168.1.254:3306/wip?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wip
    password: 123456
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait-millis: 10000
      validation-query: SELECT 1 FROM DUAL
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.1.254:9300
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
   mapper-locations: classpath*:mybatis/*.xml
   type-aliases-package: com.springcloud.content.model

