server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

spring:
  datasource:
    url: jdbc:mysql://192.168.1.254:3306/wip?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wip
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


